# Generated by Django 2.0.3 on 2018-06-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_to', to='friends.Friends')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='friends.Friends')),
            ],
        ),
    ]
