# Generated by Django 2.0.3 on 2018-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20180606_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
