# Generated by Django 2.0 on 2018-06-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20180606_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.Friends')),
            ],
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_person', to='friends.Friends'),
        ),
    ]
