# Generated by Django 2.0 on 2018-06-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_auto_20180613_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='msg_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='msg_to', to='friends.Friends'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='msg_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_from', to='friends.Friends'),
        ),
    ]
