# Generated by Django 2.0 on 2018-06-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_auto_20180614_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='msg_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_to', to='friends.Friends'),
        ),
    ]
